### ISSUE TITLE
Doesn't connect with proxy

### ISSUE THREAD

**Issue by malygin-g** [1iveowl/WebsocketClientLite.PCL#48]
Hi, I use slackconnector (https://github.com/noobot/SlackConnector/) and it can't connect with proxy:
p.s. The error seems to be with the nuget library is WebsocketClientLite.PCL
System.InvalidOperationException
HResult=0x80131509
Message=The operation is not allowed on non-connected sockets.
Source=System
StackTrace:
at System.Net.Sockets.TcpClient.GetStream()
at SocketLite.Services.TcpSocketClient.d__19.MoveNext()
at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at WebsocketClientLite.PCL.MessageWebSocketRx.d__15.MoveNext()
at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at SlackConnector.Connections.Sockets.WebSocketClientLite.d__7.MoveNext()
at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at SlackConnector.Connections.ConnectionFactory.d__0.MoveNext()
at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at SlackConnector.SlackConnector.d__5.MoveNext()
at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
at TopShelf2.SlackConnect.d__4.MoveNext() in C:\mygit\TopShelf2\TopShelf2\Program.cs:line 40

**Comment by 1iveowl** [comment]
Did you read the section in the Readme about Slack?

**Comment by Itsey** [comment]
@malygin-g did you manage to get an answer to this?  I dont think that the readme covers it and it appears that this implementation doesnt support corporate proxies.
